AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 400

Metrics/AbcSize:
  Max: 40

Style/AccessorMethodName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/RescueException:
  Enabled: false
